import { Car, CircleDollarSign, Disc, Fuel, Settings } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const automotiveConverters: Record<string, ConverterMeta> = {
  "fuel-efficiency": {
    id: "fuel-efficiency",
    slug: "fuel-efficiency",
    category: "automotive",
    subcategory: "fuel",
    keywords: [
      "fuel",
      "efficiency",
      "consumption",
      "l/100km",
      "liters",
      "km/l",
      "mpg",
      "petrol",
      "diesel",
      "gas",
      "mileage",
      "trip cost",
      "annual cost",
      "carburant",
      "kraftstoff",
      "benzina",
    ],
    icon: Fuel,
    featured: true,
  },
  "tire-sizing": {
    id: "tire-sizing",
    slug: "tire-sizing",
    category: "automotive",
    subcategory: "tires",
    keywords: [
      "tire",
      "tyre",
      "size",
      "dimensions",
      "width",
      "aspect",
      "diameter",
      "rim",
      "speedometer",
      "205/55R16",
      "pneu",
      "reifen",
      "pneumatico",
    ],
    icon: Disc,
    featured: true,
  },
  "maintenance-intervals": {
    id: "maintenance-intervals",
    slug: "maintenance-intervals",
    category: "automotive",
    subcategory: "maintenance",
    keywords: [
      "maintenance",
      "service",
      "oil change",
      "intervals",
      "schedule",
      "mfk",
      "inspection",
      "brake",
      "filter",
      "entretien",
      "wartung",
      "manutenzione",
    ],
    icon: Settings,
    featured: true,
  },
  "vehicle-financing": {
    id: "vehicle-financing",
    slug: "vehicle-financing",
    category: "automotive",
    subcategory: "financing",
    keywords: [
      "loan",
      "lease",
      "financing",
      "payment",
      "monthly",
      "chf",
      "eur",
      "auto loan",
      "car lease",
      "residual",
      "financement",
      "finanzierung",
      "finanziamento",
    ],
    icon: CircleDollarSign,
    featured: true,
  },
};
