import {
  Calendar,
  Database,
  DollarSign,
  Gauge,
  Globe,
  Heart,
  ImageIcon,
  Music,
  Palette,
  Video,
} from "lucide-react";
import type { ConverterMeta } from "@/types";

export const converterRegistry: Record<string, ConverterMeta> = {
  // Health
  bmi: {
    id: "bmi",
    slug: "bmi",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index and health category",
    category: "health",
    keywords: ["bmi", "body mass index", "weight", "health", "obesity"],
    icon: Heart,
    featured: true,
  },
  corpulence: {
    id: "corpulence",
    slug: "corpulence",
    name: "Corpulence Calculator",
    description: "Calculate your Corpulence Index (Ponderal Index)",
    category: "health",
    keywords: ["corpulence", "ponderal index", "body composition", "weight"],
    icon: Heart,
    featured: false,
  },

  // Date & Time
  age: {
    id: "age",
    slug: "age",
    name: "Age Calculator",
    description: "Calculate exact age from birthdate in years, months, and days",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["age", "birthday", "years", "months", "days", "birth date"],
    icon: Calendar,
    featured: true,
  },
  date: {
    id: "date",
    slug: "date",
    name: "Date Calculator",
    description: "Add or subtract days, weeks, months, and years from a date",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["date", "add", "subtract", "days", "weeks", "months", "years"],
    icon: Calendar,
    featured: false,
  },
  time: {
    id: "time",
    slug: "time",
    name: "Time Calculator",
    description: "Add or subtract hours, minutes, and seconds",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["time", "add", "subtract", "hours", "minutes", "seconds"],
    icon: Calendar,
    featured: false,
  },
  hours: {
    id: "hours",
    slug: "hours",
    name: "Hours Calculator",
    description: "Calculate hours between two times or dates",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["hours", "time", "duration", "work hours", "between"],
    icon: Calendar,
    featured: false,
  },
  "time-duration": {
    id: "time-duration",
    slug: "time-duration",
    name: "Time Duration Calculator",
    description: "Calculate duration between two dates and times",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["duration", "time", "between", "difference", "elapsed"],
    icon: Calendar,
    featured: false,
  },
  "time-zone": {
    id: "time-zone",
    slug: "time-zone",
    name: "Time Zone Calculator",
    description: "Convert times between different time zones",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["time zone", "convert", "utc", "gmt", "timezone"],
    icon: Calendar,
    featured: false,
  },
  "day-counter": {
    id: "day-counter",
    slug: "day-counter",
    name: "Day Counter",
    description: "Count days between dates or until a future date",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["days", "count", "between", "until", "countdown"],
    icon: Calendar,
    featured: false,
  },
  "day-of-week": {
    id: "day-of-week",
    slug: "day-of-week",
    name: "Day of the Week Calculator",
    description: "Find what day of the week any date falls on",
    category: "datetime",
    subcategory: "date-time",
    keywords: ["day", "week", "monday", "tuesday", "date", "weekday"],
    icon: Calendar,
    featured: false,
  },

  // Color
  rgb: {
    id: "rgb",
    slug: "rgb",
    name: "RGB Converter",
    description: "Convert between RGB, HEX, HSL, and CMYK color formats",
    category: "color",
    keywords: ["rgb", "hex", "color", "convert", "hsl", "cmyk"],
    icon: Palette,
    featured: true,
  },

  // Data
  "data-size": {
    id: "data-size",
    slug: "data-size",
    name: "Data Size Calculator",
    description: "Convert between bytes, KB, MB, GB, TB and more",
    category: "data",
    keywords: ["data", "size", "bytes", "kilobytes", "megabytes", "gigabytes"],
    icon: Database,
    featured: true,
  },
  bandwidth: {
    id: "bandwidth",
    slug: "bandwidth",
    name: "Bandwidth Converter",
    description: "Convert Mbps to KB/s, GB/day, TB/week and more",
    category: "data",
    keywords: ["bandwidth", "mbps", "kbps", "network", "speed", "transfer"],
    icon: Database,
    featured: false,
  },
  "download-calculator": {
    id: "download-calculator",
    slug: "download-calculator",
    name: "Download Calculator",
    description: "Calculate download time from bandwidth and file size",
    category: "data",
    keywords: ["download", "time", "bandwidth", "file size", "transfer"],
    icon: Database,
    featured: false,
  },

  // Physics
  speed: {
    id: "speed",
    slug: "speed",
    name: "Speed Converter",
    description: "Convert between m/s, km/h, mph, knots, and more",
    category: "physics",
    keywords: ["speed", "velocity", "mph", "kmh", "meters per second"],
    icon: Gauge,
    featured: true,
  },

  // Photo
  "aspect-ratio": {
    id: "aspect-ratio",
    slug: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios from width and height",
    category: "photo",
    keywords: ["aspect ratio", "width", "height", "image", "video", "screen"],
    icon: ImageIcon,
    featured: true,
  },
  "aspect-fit": {
    id: "aspect-fit",
    slug: "aspect-fit",
    name: "Aspect Fit Calculator",
    description: "Fit an image on a screen with letterboxing",
    category: "photo",
    keywords: ["aspect fit", "letterbox", "pillarbox", "screen", "resize"],
    icon: ImageIcon,
    featured: false,
  },
  composition: {
    id: "composition",
    slug: "composition",
    name: "Composition Calculator",
    description: "Calculate field of view from focal length and distance",
    category: "photo",
    keywords: ["composition", "focal length", "field of view", "crop factor"],
    icon: ImageIcon,
    featured: false,
  },
  "depth-of-field": {
    id: "depth-of-field",
    slug: "depth-of-field",
    name: "Depth of Field Calculator",
    description: "Calculate DoF from aperture, focal length, and distance",
    category: "photo",
    keywords: ["depth of field", "dof", "aperture", "bokeh", "hyperfocal"],
    icon: ImageIcon,
    featured: false,
  },
  dpi: {
    id: "dpi",
    slug: "dpi",
    name: "DPI Calculator",
    description: "Calculate megapixels from print size and DPI",
    category: "photo",
    keywords: ["dpi", "ppi", "print", "resolution", "megapixels"],
    icon: ImageIcon,
    featured: false,
  },
  "image-filesize": {
    id: "image-filesize",
    slug: "image-filesize",
    name: "Image Filesize Calculator",
    description: "Estimate image file size for JPEG, PNG, RAW formats",
    category: "photo",
    keywords: ["image", "file size", "jpeg", "png", "raw", "compression"],
    icon: ImageIcon,
    featured: false,
  },
  "light-ev": {
    id: "light-ev",
    slug: "light-ev",
    name: "Light EV Calculator",
    description: "Calculate Exposure Value from camera settings",
    category: "photo",
    keywords: ["exposure", "ev", "aperture", "shutter", "iso", "light"],
    icon: ImageIcon,
    featured: false,
  },
  megapixels: {
    id: "megapixels",
    slug: "megapixels",
    name: "Megapixel Calculator",
    description: "Calculate megapixels from width and height",
    category: "photo",
    keywords: ["megapixel", "resolution", "pixels", "image size"],
    icon: ImageIcon,
    featured: false,
  },
  "megapixel-aspects": {
    id: "megapixel-aspects",
    slug: "megapixel-aspects",
    name: "Megapixel Aspects",
    description: "View megapixels in different aspect ratios",
    category: "photo",
    keywords: ["megapixel", "aspect ratio", "resolution", "format"],
    icon: ImageIcon,
    featured: false,
  },
  "portrait-distance": {
    id: "portrait-distance",
    slug: "portrait-distance",
    name: "Portrait Distance Calculator",
    description: "Calculate ideal shooting distance for portraits",
    category: "photo",
    keywords: ["portrait", "distance", "focal length", "headshot"],
    icon: ImageIcon,
    featured: false,
  },
  "star-trails": {
    id: "star-trails",
    slug: "star-trails",
    name: "Star Trails Calculator",
    description: "Calculate exposure time for star trail rotation",
    category: "photo",
    keywords: ["star trails", "astrophotography", "long exposure", "night", "rotation"],
    icon: ImageIcon,
    featured: false,
  },
  "spot-stars": {
    id: "spot-stars",
    slug: "spot-stars",
    name: "Spot Stars Calculator",
    description: "Calculate max exposure to prevent star trailing (NPF Rule)",
    category: "photo",
    keywords: ["spot stars", "npf rule", "milky way", "astrophotography", "500 rule"],
    icon: ImageIcon,
    featured: false,
  },
  "time-lapse": {
    id: "time-lapse",
    slug: "time-lapse",
    name: "Time Lapse Calculator",
    description: "Calculate interval, clip length, and memory for time lapse",
    category: "photo",
    keywords: ["time lapse", "timelapse", "interval", "photography", "video"],
    icon: ImageIcon,
    featured: false,
  },
  "focal-equivalent": {
    id: "focal-equivalent",
    slug: "focal-equivalent",
    name: "Focal Length Equivalent",
    description: "Match settings between different sensor sizes",
    category: "photo",
    keywords: ["focal length", "equivalent", "crop factor", "sensor", "field of view"],
    icon: ImageIcon,
    featured: false,
  },
  hyperfocal: {
    id: "hyperfocal",
    slug: "hyperfocal",
    name: "Hyperfocal Distance Calculator",
    description: "Calculate hyperfocal distance for maximum depth of field",
    category: "photo",
    keywords: ["hyperfocal", "depth of field", "landscape", "sharpness", "focus"],
    icon: ImageIcon,
    featured: false,
  },
  "nd-filter": {
    id: "nd-filter",
    slug: "nd-filter",
    name: "ND Filter Calculator",
    description: "Calculate exposure time with ND filters",
    category: "photo",
    keywords: ["nd filter", "neutral density", "long exposure", "shutter speed"],
    icon: ImageIcon,
    featured: false,
  },
  "golden-hour": {
    id: "golden-hour",
    slug: "golden-hour",
    name: "Golden Hour Guide",
    description: "Calculate golden hour times based on your location",
    category: "photo",
    keywords: ["golden hour", "blue hour", "twilight", "sunrise", "sunset", "geolocation"],
    icon: ImageIcon,
    featured: false,
  },
  "circle-of-confusion": {
    id: "circle-of-confusion",
    slug: "circle-of-confusion",
    name: "Circle of Confusion Calculator",
    description: "Calculate CoC from sensor, print size, and viewing distance",
    category: "photo",
    keywords: ["circle of confusion", "coc", "depth of field", "print", "sharpness"],
    icon: ImageIcon,
    featured: false,
  },
  "advanced-dof": {
    id: "advanced-dof",
    slug: "advanced-dof",
    name: "Advanced DoF Calculator",
    description: "Depth of field with adjustable CoC for print size and viewing",
    category: "photo",
    keywords: ["depth of field", "dof", "circle of confusion", "print", "viewing distance"],
    icon: ImageIcon,
    featured: false,
  },
  "macro-dof": {
    id: "macro-dof",
    slug: "macro-dof",
    name: "Macro DoF Calculator",
    description: "Accurate depth of field for macro photography",
    category: "photo",
    keywords: ["macro", "depth of field", "magnification", "close-up", "focus stacking"],
    icon: ImageIcon,
    featured: false,
  },
  "dof-table": {
    id: "dof-table",
    slug: "dof-table",
    name: "DoF Table",
    description: "Interactive table showing DoF across apertures and distances",
    category: "photo",
    keywords: ["depth of field", "table", "aperture", "distance", "reference"],
    icon: ImageIcon,
    featured: false,
  },
  diffraction: {
    id: "diffraction",
    slug: "diffraction",
    name: "Diffraction Calculator",
    description: "Calculate when your camera becomes diffraction-limited",
    category: "photo",
    keywords: ["diffraction", "airy disk", "aperture", "sharpness", "pixel pitch"],
    icon: ImageIcon,
    featured: false,
  },
  "macro-diffraction": {
    id: "macro-diffraction",
    slug: "macro-diffraction",
    name: "Macro Diffraction Calculator",
    description: "Calculate effective aperture and diffraction in macro photography",
    category: "photo",
    keywords: ["macro", "diffraction", "effective aperture", "magnification", "sharpness"],
    icon: ImageIcon,
    featured: false,
  },

  // Music
  bpm: {
    id: "bpm",
    slug: "bpm",
    name: "BPM Calculator",
    description: "Convert BPM to Hz, bar length, and note durations",
    category: "music",
    keywords: ["bpm", "tempo", "beats per minute", "music", "rhythm"],
    icon: Music,
    featured: true,
  },

  // Video
  "video-file-size": {
    id: "video-file-size",
    slug: "video-file-size",
    name: "Video File Size Calculator",
    description: "Estimate video file size from resolution and duration",
    category: "video",
    keywords: ["video", "file size", "bitrate", "duration", "resolution"],
    icon: Video,
    featured: true,
  },
  "audio-filesize": {
    id: "audio-filesize",
    slug: "audio-filesize",
    name: "Audio File Size Calculator",
    description: "Estimate audio file size from duration and format",
    category: "video",
    keywords: ["audio", "file size", "mp3", "wav", "flac", "bitrate"],
    icon: Video,
    featured: false,
  },
  "common-bitrates": {
    id: "common-bitrates",
    slug: "common-bitrates",
    name: "Common Bitrates Reference",
    description: "Reference guide for ProRes, DNxHD, DCP, and MPEG bitrates",
    category: "video",
    keywords: ["bitrate", "prores", "dnxhd", "dcp", "mpeg", "codec"],
    icon: Video,
    featured: false,
  },
  "dcp-filesize": {
    id: "dcp-filesize",
    slug: "dcp-filesize",
    name: "DCP File Size Calculator",
    description: "Calculate Digital Cinema Package file sizes",
    category: "video",
    keywords: ["dcp", "digital cinema", "file size", "cinema"],
    icon: Video,
    featured: false,
  },
  "foot-lambert": {
    id: "foot-lambert",
    slug: "foot-lambert",
    name: "Foot-Lambert Calculator",
    description: "Calculate screen luminance for cinema projection",
    category: "video",
    keywords: ["foot-lambert", "luminance", "nits", "projection", "cinema"],
    icon: Video,
    featured: false,
  },
  "screen-size": {
    id: "screen-size",
    slug: "screen-size",
    name: "Screen Size Calculator",
    description: "Calculate screen dimensions from diagonal and aspect ratio",
    category: "video",
    keywords: ["screen", "diagonal", "width", "height", "aspect ratio"],
    icon: Video,
    featured: false,
  },
  "video-bitrate": {
    id: "video-bitrate",
    slug: "video-bitrate",
    name: "Video Bitrate Calculator",
    description: "Estimate video bitrate based on resolution and codec",
    category: "video",
    keywords: ["bitrate", "video", "h264", "h265", "prores", "codec"],
    icon: Video,
    featured: false,
  },
  "frame-rate": {
    id: "frame-rate",
    slug: "frame-rate",
    name: "Frame Rate Converter",
    description: "Convert between frame rates with ffmpeg commands",
    category: "video",
    keywords: ["frame rate", "fps", "ffmpeg", "convert", "video"],
    icon: Video,
    featured: false,
  },

  // Web
  "url-encoder": {
    id: "url-encoder",
    slug: "url-encoder",
    name: "URL Encoder",
    description: "Encode and decode URLs and special characters",
    category: "web",
    keywords: ["url", "encode", "decode", "uri", "percent encoding"],
    icon: Globe,
    featured: true,
  },
  csp: {
    id: "csp",
    slug: "csp",
    name: "CSP Generator",
    description: "Generate Content Security Policy headers",
    category: "web",
    keywords: ["csp", "content security policy", "security", "headers", "xss"],
    icon: Globe,
    featured: false,
  },
  "redirect-check": {
    id: "redirect-check",
    slug: "redirect-check",
    name: "Redirect Checker",
    description: "Check HTTP redirect chains and status codes",
    category: "web",
    keywords: ["redirect", "http", "301", "302", "url", "seo"],
    icon: Globe,
    featured: false,
  },
  "spf-check": {
    id: "spf-check",
    slug: "spf-check",
    name: "SPF Record Checker",
    description: "Analyze SPF records for email authentication",
    category: "web",
    keywords: ["spf", "email", "dns", "sender policy framework", "security"],
    icon: Globe,
    featured: false,
  },
  "https-check": {
    id: "https-check",
    slug: "https-check",
    name: "HTTPS Security Checker",
    description: "Check security headers and TLS configuration",
    category: "web",
    keywords: ["https", "ssl", "tls", "security headers", "hsts"],
    icon: Globe,
    featured: false,
  },
  "html-encoder": {
    id: "html-encoder",
    slug: "html-encoder",
    name: "HTML Encoder",
    description: "Encode and decode HTML entities",
    category: "web",
    keywords: ["html", "encode", "decode", "entities", "escape"],
    icon: Globe,
    featured: false,
  },
  "html-chars": {
    id: "html-chars",
    slug: "html-chars",
    name: "HTML Character Map",
    description: "Browse and copy HTML character entities",
    category: "web",
    keywords: ["html", "entities", "characters", "symbols", "unicode"],
    icon: Globe,
    featured: false,
  },
  "emoji-chars": {
    id: "emoji-chars",
    slug: "emoji-chars",
    name: "Emoji Character Map",
    description: "Browse and copy emoji with codes",
    category: "web",
    keywords: ["emoji", "unicode", "html", "copy", "emoticons"],
    icon: Globe,
    featured: false,
  },
  "seo-performance": {
    id: "seo-performance",
    slug: "seo-performance",
    name: "SEO Performance Analyzer",
    description: "Analyze page SEO metrics and get recommendations",
    category: "web",
    keywords: ["seo", "performance", "optimization", "meta tags", "content"],
    icon: Globe,
    featured: false,
  },

  // Finance
  mortgage: {
    id: "mortgage",
    slug: "mortgage",
    name: "Mortgage Calculator",
    description: "Calculate monthly payments, view amortization schedule, and visualize your loan",
    category: "finance",
    subcategory: "loans",
    keywords: [
      "mortgage",
      "home loan",
      "amortization",
      "monthly payment",
      "interest rate",
      "down payment",
    ],
    icon: DollarSign,
    featured: true,
  },
  "compound-interest": {
    id: "compound-interest",
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest on investments with regular contributions",
    category: "finance",
    subcategory: "interest",
    keywords: ["compound interest", "investment", "savings", "growth", "contributions"],
    icon: DollarSign,
    featured: true,
  },
  loan: {
    id: "loan",
    slug: "loan",
    name: "Loan Calculator",
    description: "Calculate monthly payments for personal, auto, or any loan type",
    category: "finance",
    subcategory: "loans",
    keywords: ["loan", "personal loan", "auto loan", "monthly payment", "amortization"],
    icon: DollarSign,
    featured: false,
  },
  retirement: {
    id: "retirement",
    slug: "retirement",
    name: "Retirement Calculator",
    description: "Plan your retirement with savings projections and income planning",
    category: "finance",
    subcategory: "investments",
    keywords: ["retirement", "401k", "pension", "savings", "social security", "investment"],
    icon: DollarSign,
    featured: true,
  },
  salary: {
    id: "salary",
    slug: "salary",
    name: "Salary & Tax Calculator",
    description: "Calculate take-home pay after federal, state taxes, and FICA",
    category: "finance",
    subcategory: "taxes",
    keywords: ["salary", "tax", "paycheck", "take home", "income", "net pay", "federal", "state"],
    icon: DollarSign,
    featured: true,
  },
  tip: {
    id: "tip",
    slug: "tip",
    name: "Tip Calculator",
    description: "Calculate tip amount and split bills between multiple people",
    category: "finance",
    subcategory: "everyday",
    keywords: ["tip", "gratuity", "restaurant", "bill split", "service"],
    icon: DollarSign,
    featured: false,
  },
  "savings-goal": {
    id: "savings-goal",
    slug: "savings-goal",
    name: "Savings Goal Calculator",
    description: "Calculate how long to reach your savings goal with regular contributions",
    category: "finance",
    subcategory: "investments",
    keywords: ["savings", "goal", "investment", "planning", "future"],
    icon: DollarSign,
    featured: false,
  },
  inflation: {
    id: "inflation",
    slug: "inflation",
    name: "Inflation Calculator",
    description: "Calculate the impact of inflation on purchasing power over time",
    category: "finance",
    subcategory: "investments",
    keywords: ["inflation", "purchasing power", "CPI", "cost of living"],
    icon: DollarSign,
    featured: false,
  },
  roi: {
    id: "roi",
    slug: "roi",
    name: "ROI Calculator",
    description: "Calculate return on investment and annualized returns",
    category: "finance",
    subcategory: "investments",
    keywords: ["roi", "return on investment", "profit", "investment return"],
    icon: DollarSign,
    featured: false,
  },
  "break-even": {
    id: "break-even",
    slug: "break-even",
    name: "Break-Even Calculator",
    description: "Calculate break-even point for your business",
    category: "finance",
    subcategory: "business",
    keywords: ["break even", "business", "costs", "revenue", "profit"],
    icon: DollarSign,
    featured: false,
  },
  "profit-margin": {
    id: "profit-margin",
    slug: "profit-margin",
    name: "Profit Margin Calculator",
    description: "Calculate gross, operating, and net profit margins",
    category: "finance",
    subcategory: "business",
    keywords: ["profit margin", "gross margin", "net margin", "markup"],
    icon: DollarSign,
    featured: false,
  },
  discount: {
    id: "discount",
    slug: "discount",
    name: "Discount Calculator",
    description: "Calculate discounts, sale prices, and savings",
    category: "finance",
    subcategory: "everyday",
    keywords: ["discount", "sale", "percent off", "savings", "price"],
    icon: DollarSign,
    featured: false,
  },
  currency: {
    id: "currency",
    slug: "currency",
    name: "Currency Converter",
    description: "Convert between major world currencies",
    category: "finance",
    subcategory: "conversion",
    keywords: ["currency", "exchange rate", "forex", "money", "conversion"],
    icon: DollarSign,
    featured: true,
  },
};

export function getConverterById(id: string): ConverterMeta | undefined {
  return converterRegistry[id];
}

export function getConvertersByCategory(categoryId: string): ConverterMeta[] {
  return Object.values(converterRegistry).filter((converter) => converter.category === categoryId);
}

export function getFeaturedConverters(): ConverterMeta[] {
  return Object.values(converterRegistry).filter((c) => c.featured);
}

export function getConvertersBySubcategory(
  categoryId: string,
  subcategoryId: string
): ConverterMeta[] {
  return Object.values(converterRegistry).filter(
    (converter) => converter.category === categoryId && converter.subcategory === subcategoryId
  );
}

export function getConvertersByCategoryGrouped(categoryId: string): Map<string, ConverterMeta[]> {
  const converters = getConvertersByCategory(categoryId);
  const grouped = new Map<string, ConverterMeta[]>();

  for (const converter of converters) {
    const subcategory = converter.subcategory ?? "uncategorized";
    const existing = grouped.get(subcategory) ?? [];
    grouped.set(subcategory, [...existing, converter]);
  }

  return grouped;
}
