import { Scale, Utensils } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const cookingConverters: Record<string, ConverterMeta> = {
  "cooking-units": {
    id: "cooking-units",
    slug: "cooking-units",
    category: "cooking",
    subcategory: "units",
    keywords: [
      "cooking",
      "units",
      "convert",
      "cups",
      "tablespoon",
      "teaspoon",
      "ml",
      "grams",
      "liters",
      "ounces",
      "volume",
      "weight",
      "metric",
      "imperial",
      "kitchen",
      "baking",
      "density",
      "flour",
      "sugar",
    ],
    icon: Scale,
    featured: true,
  },
  "recipe-scaler": {
    id: "recipe-scaler",
    slug: "recipe-scaler",
    category: "cooking",
    subcategory: "recipes",
    keywords: [
      "recipe",
      "scale",
      "scaler",
      "servings",
      "multiply",
      "divide",
      "cooking",
      "baking",
      "portion",
      "adjust",
      "double",
      "half",
      "ingredients",
      "kitchen",
      "conversion",
    ],
    icon: Utensils,
    featured: true,
  },
};
