import { HardDrive, Receipt, Server } from "lucide-react";
import type { ConverterMeta } from "@/types";

export const infrastructureConverters: Record<string, ConverterMeta> = {
  "vm-storage-calculator": {
    id: "vm-storage-calculator",
    slug: "vm-storage-calculator",
    category: "infrastructure",
    subcategory: "virtualization",
    keywords: [
      "vm",
      "virtual machine",
      "storage",
      "vmware",
      "vsphere",
      "esx",
      "esxi",
      "capacity",
      "provisioning",
      "thin provisioning",
      "datastore",
      "swap",
      "snapshot",
    ],
    icon: HardDrive,
    featured: true,
  },
  "k8s-capacity-calculator": {
    id: "k8s-capacity-calculator",
    slug: "k8s-capacity-calculator",
    category: "infrastructure",
    subcategory: "containers",
    keywords: [
      "kubernetes",
      "k8s",
      "capacity",
      "node sizing",
      "cluster",
      "pods",
      "containers",
      "resources",
      "cpu",
      "memory",
      "scheduling",
      "allocatable",
      "utilization",
    ],
    icon: Server,
    featured: true,
  },
  "server-virtualization-calculator": {
    id: "server-virtualization-calculator",
    slug: "server-virtualization-calculator",
    category: "infrastructure",
    subcategory: "virtualization",
    keywords: [
      "vmware",
      "esx",
      "esxi",
      "host",
      "sizing",
      "virtualization",
      "n+1",
      "ha",
      "high availability",
      "capacity",
      "vcpu",
      "consolidation",
    ],
    icon: Server,
    featured: true,
  },
  "vmware-licensing-calculator": {
    id: "vmware-licensing-calculator",
    slug: "vmware-licensing-calculator",
    category: "infrastructure",
    subcategory: "vmware",
    keywords: [
      "vmware",
      "vcf",
      "vvf",
      "licensing",
      "subscription",
      "vsan",
      "cost",
      "broadcom",
      "cloud foundation",
      "vsphere foundation",
    ],
    icon: Receipt,
    featured: true,
  },
  // Virtualization Cost Calculator - Phase 30
};
